services:
  app:
    build: .
    env_file: .env.docker
    depends_on:
      - postgres
    entrypoint: ["python3", "-m", "app"]

  postgres:
    image: postgres:15
    env_file: .env.docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  telegram_bot:
    build: .
    env_file: .env.docker
    entrypoint: ["python3", "-m", "bot.telegram_bot"]

  api:
    build: .
    env_file: .env.docker
    entrypoint: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"

volumes:
  pgdata: